server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    # This will disable the tomcat server
    web-application-type: servlet # use "none" for disable the tomcat server